In [ ]:
from ultralytics import YOLO
# Export to TensorRT engine using train subset for calibration => use clean validation set with model.val() for benchmarking
model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)
model.export(
    format="engine",
    imgsz=640,
    half=False,
    int8=True,
    dynamic=False,
    simplify=True,
    # nms=True,
    batch=1,
    data="/home/omni/Programming/QRID/QRID/my_benchmark_yaml/clean_coco.yaml",
    fraction=0.1,
    device="cuda"
)

Ultralytics 8.3.109 🚀 Python-3.12.3 torch-2.6.0+cu124 CUDA:0 (NVIDIA GeForce RTX 2070, 7789MiB)

YOLOv8n summary (fused): 72 layers, 3,151,904 parameters, 0 gradients, 8.7 GFLOPs

PyTorch: starting from 'yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)

ONNX: starting export with onnx 1.17.0 opset 19...
ONNX: slimming with onnxslim 0.1.50...
ONNX: export success ✅ 10.5s, saved as 'yolov8n.onnx' (12.1 MB)

TensorRT: starting export with TensorRT 10.9.0.34...
TensorRT: collecting INT8 calibration images from 'data=/home/omni/Programming/QRID/QRID/my_benchmark_yaml/clean_coco.yaml'

Scanning /home/omni/Programming/QRID/datasets/coco/labels/val2017... 496 images, 4 backgrounds, 0 corrupt: 100%|██████████| 500/500 [00:00<00:00, 2508.29it/s]

New cache created: /home/omni/Programming/QRID/datasets/coco/labels/val2017.cache

[04/30/2025-19:53:50] [TRT] [I] The logger passed into createInferBuilder differs from one already provided for an existing builder, runtime, or refitter. Uses of the global logger, returned by nvinfer1::getLogger(), will return the existing value.
[04/30/2025-19:53:52] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU -1138, GPU +164, now: CPU 5986, GPU 942 (MiB)
[04/30/2025-19:53:52] [TRT] [I] ----------------------------------------------------------------
[04/30/2025-19:53:52] [TRT] [I] Input filename:   yolov8n.onnx
[04/30/2025-19:53:52] [TRT] [I] ONNX IR version:  0.0.9
[04/30/2025-19:53:52] [TRT] [I] Opset version:    19
[04/30/2025-19:53:52] [TRT] [I] Producer name:    pytorch
[04/30/2025-19:53:52] [TRT] [I] Producer version: 2.6.0
[04/30/2025-19:53:52] [TRT] [I] Domain:
[04/30/2025-19:53:52] [TRT] [I] Model version:    0
[04/30/2025-19:53:52] [TRT] [I] Doc string:
[04/30/2025-19:53:52] [TRT] [I] ----------------------------------------------------------------
TensorRT: input "images" with shape(-1, 3, -1, -1) DataType.FLOAT
TensorRT: output "output0" with shape(-1, 84, -1) DataType.FLOAT
TensorRT: WARNING ⚠️ 'dynamic=True' model requires max batch size, i.e. 'batch=16'
TensorRT: building INT8 engine as yolov8n.engine
[04/30/2025-19:53:52] [TRT] [I] BuilderFlag::kTF32 is set but hardware does not support TF32. Disabling TF32.
[04/30/2025-19:53:52] [TRT] [I] Reading Calibration Cache for calibrator: EntropyCalibration2
[04/30/2025-19:53:52] [TRT] [I] Generated calibration scales using calibration cache. Make sure that calibration cache has latest scales.
[04/30/2025-19:53:52] [TRT] [I] To regenerate calibration cache, please delete the existing one. TensorRT will generate a new calibration cache.
[04/30/2025-19:53:52] [TRT] [I] BuilderFlag::kTF32 is set but hardware does not support TF32. Disabling TF32.
[04/30/2025-19:53:52] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[04/30/2025-19:56:04] [TRT] [I] Detected 1 inputs and 3 output network tensors.
[04/30/2025-19:56:07] [TRT] [I] Total Host Persistent Memory: 341680 bytes
[04/30/2025-19:56:07] [TRT] [I] Total Device Persistent Memory: 1799168 bytes
[04/30/2025-19:56:07] [TRT] [I] Max Scratch Memory: 0 bytes
[04/30/2025-19:56:07] [TRT] [I] [BlockAssignment] Started assigning block shifts. This will take 139 steps to complete.
[04/30/2025-19:56:07] [TRT] [I] [BlockAssignment] Algorithm ShiftNTopDown took 10.3846ms to assign 10 blocks to 139 nodes requiring 12723200 bytes.
[04/30/2025-19:56:07] [TRT] [I] Total Activation Memory: 12722176 bytes
[04/30/2025-19:56:07] [TRT] [I] Total Weights Memory: 3495940 bytes
[04/30/2025-19:56:07] [TRT] [I] Engine generation completed in 135.03 seconds.
[04/30/2025-19:56:07] [TRT] [I] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 6 MiB, GPU 336 MiB
TensorRT: export success ✅ 147.5s, saved as 'yolov8n.engine' (5.7 MB)

Export complete (147.6s)
Results saved to /home/omni/Programming/QRID/QRID
Predict:         yolo predict task=detect model=yolov8n.engine imgsz=640 int8
Validate:        yolo val task=detect model=yolov8n.engine imgsz=640 data=coco.yaml int8
Visualize:       https://netron.app

'yolov8n.engine'

In [ ]:
from functions.benchmark import benchmark
benchmark_results = benchmark(
    model='/home/omni/Programming/QRID/QRID/yolov8n.engine',
    kwargs={
        "data": "/home/omni/Programming/QRID/QRID/my_benchmark_yaml/clean_coco.yaml",
        "device": "cuda",
    }
)
benchmark_results

Model is not a YOLO object. Please provide a valid YOLO model.

In [3]:
from ultralytics.utils.benchmarks import benchmark
benchmark(
    model="yolov8n.pt",
    data="/home/omni/Programming/QRID/QRID/my_benchmark_yaml/clean_coco.yaml",
    imgsz=640,
    half=False,
    int8=True,
    device="cuda",
    verbose=False,
    format="engine",
) # benchmark function ensures using batch size 1

Setup complete ✅ (12 CPUs, 31.2 GB RAM, 433.9/937.8 GB disk)

Benchmarks complete for yolov8n.pt on /home/omni/Programming/QRID/QRID/my_benchmark_yaml/clean_coco.yaml at imgsz=640 (238.94s)
Benchmarks legend:  - ✅ Success  - ❎ Export passed but validation failed  - ❌️ Export failed
     Format Status❔  Size (MB)  metrics/mAP50-95(B)  Inference time (ms/im)     FPS
0  TensorRT       ✅        5.8               0.3229                    1.63  614.98

     Format Status❔  Size (MB)  metrics/mAP50-95(B)  Inference time (ms/im)     FPS
0  TensorRT       ✅        5.8               0.3229                    1.63  614.98

In [4]:
from ultralytics.utils.benchmarks import benchmark
benchmark(
    model="yolov8n.pt",
    data="coco.yaml",
    imgsz=640,
    half=False,
    device="cuda",
    verbose=False,
    format="engine",
) # benchmark function ensures using batch size 1

Setup complete ✅ (12 CPUs, 31.2 GB RAM, 478.7/937.8 GB disk)

Benchmarks complete for yolov8n.pt on coco.yaml at imgsz=640 (155.21s)
Benchmarks legend:  - ✅ Success  - ❎ Export passed but validation failed  - ❌️ Export failed
     Format Status❔  Size (MB)  metrics/mAP50-95(B)  Inference time (ms/im)     FPS
0  TensorRT       ✅       19.3                0.371                    2.51  398.05

     Format Status❔  Size (MB)  metrics/mAP50-95(B)  Inference time (ms/im)     FPS
0  TensorRT       ✅       19.3                0.371                    2.51  398.05

In [5]:
from ultralytics.utils.benchmarks import benchmark
benchmark(
    model="yolov8n.pt",
    data="coco.yaml",
    imgsz=640,
    half=True,
    device="cuda",
    verbose=False,
    format="engine",
) # benchmark function ensures using batch size 1

Setup complete ✅ (12 CPUs, 31.2 GB RAM, 478.8/937.8 GB disk)

Benchmarks complete for yolov8n.pt on coco.yaml at imgsz=640 (300.01s)
Benchmarks legend:  - ✅ Success  - ❎ Export passed but validation failed  - ❌️ Export failed
     Format Status❔  Size (MB)  metrics/mAP50-95(B)  Inference time (ms/im)     FPS
0  TensorRT       ✅        8.8                0.371                    1.76  569.31

     Format Status❔  Size (MB)  metrics/mAP50-95(B)  Inference time (ms/im)     FPS
0  TensorRT       ✅        8.8                0.371                    1.76  569.31

In [6]:
from ultralytics.utils.benchmarks import benchmark
benchmark(
    model="yolov8n.pt",
    data="/home/omni/Programming/QRID/QRID/my_benchmark_yaml/coco_augmented_25.yaml",
    imgsz=640,
    half=False,
    int8=True,
    device="cuda",
    verbose=False,
    format="engine",
) # benchmark function ensures using batch size 1

Setup complete ✅ (12 CPUs, 31.2 GB RAM, 478.9/937.8 GB disk)

Benchmarks complete for yolov8n.pt on /home/omni/Programming/QRID/QRID/my_benchmark_yaml/coco_augmented_25.yaml at imgsz=640 (311.55s)
Benchmarks legend:  - ✅ Success  - ❎ Export passed but validation failed  - ❌️ Export failed
     Format Status❔  Size (MB)  metrics/mAP50-95(B)  Inference time (ms/im)     FPS
0  TensorRT       ✅        5.8               0.2973                    1.65  606.14

     Format Status❔  Size (MB)  metrics/mAP50-95(B)  Inference time (ms/im)     FPS
0  TensorRT       ✅        5.8               0.2973                    1.65  606.14

In [7]:
from ultralytics.utils.benchmarks import benchmark
benchmark(
    model="yolov8n.pt",
    data="/home/omni/Programming/QRID/QRID/my_benchmark_yaml/coco_augmented_50.yaml",
    imgsz=640,
    half=False,
    int8=True,
    device="cuda",
    verbose=False,
    format="engine",
) # benchmark function ensures using batch size 1

Setup complete ✅ (12 CPUs, 31.2 GB RAM, 478.9/937.8 GB disk)

Benchmarks complete for yolov8n.pt on /home/omni/Programming/QRID/QRID/my_benchmark_yaml/coco_augmented_50.yaml at imgsz=640 (244.02s)
Benchmarks legend:  - ✅ Success  - ❎ Export passed but validation failed  - ❌️ Export failed
     Format Status❔  Size (MB)  metrics/mAP50-95(B)  Inference time (ms/im)     FPS
0  TensorRT       ✅        5.7               0.2753                    1.65  606.11

     Format Status❔  Size (MB)  metrics/mAP50-95(B)  Inference time (ms/im)     FPS
0  TensorRT       ✅        5.7               0.2753                    1.65  606.11

In [8]:
from ultralytics.utils.benchmarks import benchmark
benchmark(
    model="yolov8n.pt",
    data="/home/omni/Programming/QRID/QRID/my_benchmark_yaml/coco_augmented_75.yaml",
    imgsz=640,
    half=False,
    int8=True,
    device="cuda",
    verbose=False,
    format="engine",
) # benchmark function ensures using batch size 1

Setup complete ✅ (12 CPUs, 31.2 GB RAM, 479.0/937.8 GB disk)

Benchmarks complete for yolov8n.pt on /home/omni/Programming/QRID/QRID/my_benchmark_yaml/coco_augmented_75.yaml at imgsz=640 (237.56s)
Benchmarks legend:  - ✅ Success  - ❎ Export passed but validation failed  - ❌️ Export failed
     Format Status❔  Size (MB)  metrics/mAP50-95(B)  Inference time (ms/im)     FPS
0  TensorRT       ✅        5.7               0.2973                    1.64  609.93

     Format Status❔  Size (MB)  metrics/mAP50-95(B)  Inference time (ms/im)     FPS
0  TensorRT       ✅        5.7               0.2973                    1.64  609.93

In [9]:
engine = YOLO("/home/omni/Programming/QRID/QRID/yolov8n.engine", task="detect")

In [ ]:
moedl

WARNING ⚠️ 'save_hybrid' is deprecated and will be removed in in the future.
Ultralytics 8.3.109 🚀 Python-3.12.3 torch-2.6.0+cu124 CUDA:0 (NVIDIA GeForce RTX 2070, 7789MiB)
YOLOv8n summary (fused): 72 layers, 3,151,904 parameters, 0 gradients, 8.7 GFLOPs

val: Scanning /home/omni/Programming/QRID/datasets/coco/labels/val2017.cache... 4952 images, 48 backgrounds, 0 corrupt: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):  27%|██▋       | 1348/5000 [00:11<00:31, 115.26it/s]

KeyboardInterrupt: